/* empty css                                   */
import { c as createAstro, d as createComponent, r as renderTemplate, g as renderComponent, h as renderHead } from '../astro_wFK4WpfL.mjs';
import 'kleur/colors';
import 'html-escaper';
import 'clsx';
import { c as create_ssr_component, e as escape, a as etapas, N as NavBar } from './conexionhumana_tFho6f2X.mjs';
/* empty css                                */

/* src/components/HerramientaGuiada.svelte generated by Svelte v4.2.8 */

const HerramientaGuiada = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let count = 0;
	let firstRow = "";
	let secondRow = "";
	let thirdRow = "";
	let fourthRow = "";

	return `<section class="flex flex-col gap-40 items-center"><article class="ctos flex gap-10 pt-40"><button class="flex gap-4 items-center" data-svelte-h="svelte-105jucg"><figure><img src="./public/arrow-left.svg" alt="Flecha de Volver"></figure>
      Volver Atrás</button></article> <section class="flex"><h4 class="line_1 animated text-[--nexusBlue] text-[300px] leading-[60px] tracking-[-120px]" style="white-space: pre-line;"><!-- HTML_TAG_START -->${firstRow}<!-- HTML_TAG_END --> <br> <!-- HTML_TAG_START -->${secondRow}<!-- HTML_TAG_END --> <br> <!-- HTML_TAG_START -->${thirdRow}<!-- HTML_TAG_END --> <br> <!-- HTML_TAG_START -->${fourthRow}<!-- HTML_TAG_END --></h4></section></section> ${`<h1 class="text-3xl mb-6 mt-40">${escape(etapas[count].pregunta)}</h1> <h3 class="text-gray-400 text-center max-w-[1024px] text-xl mb-10">${escape(etapas[count].ejemplo)}</h3> <article class="ctas flex gap-10 mb-20"><button class="px-8 py-4 border-black text-xl border-2 hover:bg-[--nexusBlue] hover:text-white duration-200 hover:border-[--nexusBlue]">${escape(etapas[count].respuesta[0])}</button> <button class="px-8 py-4 border-black text-xl border-2 hover:bg-[--nexusBlue] hover:text-white duration-200 hover:border-[--nexusBlue]">${escape(etapas[count].respuesta[1])}</button> <button class="px-8 py-4 border-black text-xl border-2 hover:bg-[--nexusBlue] hover:text-white duration-200 hover:border-[--nexusBlue]">${escape(etapas[count].respuesta[2])}</button> <button class="px-8 py-4 border-black text-xl border-2 hover:bg-[--nexusBlue] hover:text-white duration-200 hover:border-[--nexusBlue]">${escape(etapas[count].respuesta[3])}</button></article>`
	} ${``}`;
});

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(raw || cooked.slice()) }));
var _a;
const $$Astro = createAstro();
const $$Herramienta = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Herramienta;
  return renderTemplate(_a || (_a = __template(['<script type="module"><\/script> <html lang="es"> <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Actualizaci\xF3n en Tiempo Real</title><link rel="icon" href="./public/favicon.svg">', '</head> <body> <header class="wrap z-1"> ', ' <a href="herramientaavanzada"><span class="py-4 px-6 border-2 border-[--nexusBlue] highlight_small hover:bg-[--nexusBlue] duration-200 hover:text-white top-40 right-10 fixed">Modo Manual</span></a> </header> <main class="w-full flex items-center py-[50px] flex-col"> ', " </main> </body></html>"])), renderHead(), renderComponent($$result, "NavBar", NavBar, { "nav": "/herramienta" }), renderComponent($$result, "HerramientaDes", HerramientaGuiada, { "client:load": true, "client:component-hydration": "load", "client:component-path": "/Users/Jaime/Documents/PROGRAMACIO\u0301N/astro/nexus/src/components/HerramientaGuiada.svelte", "client:component-export": "default" }));
}, "/Users/Jaime/Documents/PROGRAMACIO\u0301N/astro/nexus/src/pages/herramienta.astro", void 0);

const $$file = "/Users/Jaime/Documents/PROGRAMACIÓN/astro/nexus/src/pages/herramienta.astro";
const $$url = "/herramienta";

export { $$Herramienta as default, $$file as file, $$url as url };
